# prepoulate database
City.first_or_create(name: 'Istanbul')
City.first_or_create(name: 'Moscow')
City.first_or_create(name: 'London')
City.first_or_create(name: 'Saint Petersburg')
City.first_or_create(name: 'Berlin')
City.first_or_create(name: 'Madrid')
City.first_or_create(name: 'Kiev')
City.first_or_create(name: 'Rome')
City.first_or_create(name: 'Paris')
City.first_or_create(name: 'Minsk')
City.first_or_create(name: 'Bucharest')
City.first_or_create(name: 'Vienna')
City.first_or_create(name: 'Budapest')
City.first_or_create(name: 'Hamburg')
City.first_or_create(name: 'Warsaw')
City.first_or_create(name: 'Barcelona')
City.first_or_create(name: 'Munich')
City.first_or_create(name: 'Kharkiv')
City.first_or_create(name: 'Milan')
City.first_or_create(name: 'Prague')
City.first_or_create(name: 'Sofia')
City.first_or_create(name: 'Nizhny Novgorod')
City.first_or_create(name: 'Kazan')
City.first_or_create(name: 'Brussels')
City.first_or_create(name: 'Samara')
City.first_or_create(name: 'Belgrade')
City.first_or_create(name: 'Birmingham')
City.first_or_create(name: 'Tbilisi')
City.first_or_create(name: 'Ufa')
City.first_or_create(name: 'Cologne')
City.first_or_create(name: 'Perm')
City.first_or_create(name: 'Voronezh')
City.first_or_create(name: 'Volgograd')
City.first_or_create(name: 'Odessa')
City.first_or_create(name: 'Dnipro')
City.first_or_create(name: 'Naples')
